scrape_configs:
  - job_name: 'ipmi'
    scrape_interval: 200s
    scrape_timeout: 200s
    file_sd_configs:
        - files :
          - impi_sd.json
    metrics_path: /ipmi
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmpexporter:9116
