discoveries:
  switch:
    refresh_interval: 5000
    targets_file_name: "switches"
    netbox_host: "uri"
    netbox_api_token: "token"
    switches:
      - name: "f5"
        manufacturer: "f5"
      - name: "asr04"
        manufacturer: "cisco"
      - name: "asr01"
        manufacturer: "cisco"
